### ISSUE TITLE
some issues with fepx installation

### ISSUE THREAD

**Issue by sajutabraham** [acmelab-ua/FEPX#20]
I have installed the fepx-1.1.1. My system already has neper-4.1.2. But while checking fepx installation status, it shows Failure to open 'simulation.msh' file. What shall I do? I am just fresh in this field but wanted to learn it thoroughly. Can somebody help?

**Comment by mkasemer** [comment]
@sajutabraham: Your description does not provide enough information to accurately assess the problem.

However, there is a known compatibility issue between newer versions of Neper and the current public version of FEPX. We are working on a new release hopefully for later this week that will resolve this issue.

**Comment by sajutabraham** [comment]
Please see the attached screenshot
![Screenshot (5)](https://user-images.githubusercontent.com/85570522/121211778-63370100-c89a-11eb-897d-bb9c85ad281c.png)
.

**Comment by mkasemer** [comment]
@sajutabraham: This, again, does not provide enough information to diagnose the problem. At the very least, the input files for the simulation should be attached, or the Neper commands used to generate the input.

**Comment by mkasemer** [comment]
@sajutabraham: Since this is seemingly an issue with your Neper installation, I am closing the issue. Please post any followups to the discussion forum.
