### ISSUE TITLE
10000 cycles of cyclic loading

### ISSUE THREAD

**Issue by Ming-is** [acmelab-ua/FEPX#24]
I'm trying to use the restart module of fepx to simulate 10000 cycles of cyclic loading, but I can only calculate one cycle at a time. It seems that I can only manually add the cycle N file to simulate the cycles, which is too inefficient.
Does fepx have any instructions or methods to help quickly simulate a large number of cycles of cyclic loading
I look forward to your reply,
thanks

**Comment by rquey** [comment]
@mkasemer, this issue can be deleted (duplicates #26).
