### ISSUE TITLE
Unable to run example 1

### ISSUE THREAD

**Issue by fzw9381** [acmelab-ua/FEPX#6]
I am in the process of learning to use FEPX. When I tried to run example 1, an error occurred.
The neper -S command prompts that the file cannot be read.
<img width="713" alt="捕获" src="https://user-images.githubusercontent.com/56809459/111733743-8bbee880-88b3-11eb-8269-886bdb8a0754.PNG">

**Comment by rquey** [comment]
This is not sufficient information. Please provide your commands and all of the terminal output.

**Comment by fzw9381** [comment]
First I ran runexample.sh in the case folder (1_uniaxial), and the calculation was successfully completed. But when I run postprocess.sh, the command line terminal prompts the following information:

cpfem@cpfem:~/examples/1_uniaxial$ ./postprocess.sh 

========================    N   e   p   e   r    =======================
Info   : A software package for polycrystal generation and meshing.
Info   : Version 3.5.3-209-neper-fepx
Info   : Built with: gsl|muparser|opengjk|openmp|nlopt
Info   : Running on 4 threads.
Info   : <http://neper.info>
Info   : Copyright (C) 2003-2020, and GNU GPL'd, by Romain Quey.
Info   : No initialization file found (`/home/cpfem/.neperrc').
Info   : ---------------------------------------------------------------
Info   : MODULE  -S loaded with arguments:
Info   : [ini file] (none)
Info   : [com line] .
Info   : ---------------------------------------------------------------
Info   : Reading input data...
Info   :   - Reading arguments...
Info   : Writing simulation directory from FEPX raw result directory...
Info   :     [o] Writing directory `/home/cpfem/examples/1_uniaxial.sim'...
Info   :   - Parsing FEPX results...
Info   :     [i] Parsing file `/home/cpfem/examples/1_uniaxial/post.report'...
var = printed_steps
Error  :     > Failed to read file.
./postprocess.sh：行 12: 64461 已放弃               neper -S .

========================    N   e   p   e   r    =======================
Info   : A software package for polycrystal generation and meshing.
Info   : Version 3.5.3-209-neper-fepx
Info   : Built with: gsl|muparser|opengjk|openmp|nlopt
Info   : Running on 4 threads.
Info   : <http://neper.info>
Info   : Copyright (C) 2003-2020, and GNU GPL'd, by Romain Quey.
Info   : Ignoring initialization file.
Info   : ---------------------------------------------------------------
Info   : MODULE  -V loaded with arguments:
Info   : [ini file] (none)
Info   : [com line] ../1_uniaxial.sim -simstep 4 -datanodecoo coo
         -dataelt1drad 0.004 -dataelt3dedgerad 0.0015 -datanodecoofact 10
         -dataelt3dcol stress33 -dataeltscaletitle Stress 33 (MPa)
         -dataeltscale 0:1000 -showelt1d all -cameraangle 13.5 -imagesize
         800:800 -print 1_s33_deform
Info   : ---------------------------------------------------------------
Error  : ../1_uniaxial.sim: no such file.
./postprocess.sh：行 19: 64465 已放弃               neper --rcfile none -V ../1_uniaxial.sim -simstep 4 -datanodecoo coo -dataelt1drad 0.004 -dataelt3dedgerad 0.0015 -datanodecoofact 10 -dataelt3dcol stress33 -dataeltscaletitle "Stress 33 (MPa)" -dataeltscale 0:1000 -showelt1d all -cameraangle 13.5 -imagesize 800:800 -print 1_s33_deform

========================    N   e   p   e   r    =======================
Info   : A software package for polycrystal generation and meshing.
Info   : Version 3.5.3-209-neper-fepx
Info   : Built with: gsl|muparser|opengjk|openmp|nlopt
Info   : Running on 4 threads.
Info   : <http://neper.info>
Info   : Copyright (C) 2003-2020, and GNU GPL'd, by Romain Quey.
Info   : Ignoring initialization file.
Info   : ---------------------------------------------------------------
Info   : MODULE  -V loaded with arguments:
Info   : [ini file] (none)
Info   : [com line] ../1_uniaxial.sim -simstep 4 -datanodecoo coo
         -dataelt1drad 0.004 -dataelt3dedgerad 0.0015 -datanodecoofact 10
         -dataelt3dcol strain-el33 -dataeltscaletitle Strain 33 (-)
         -dataeltscale 0.000:0.001:0.002:0.003:0.004 -showelt1d all
         -cameraangle 13.5 -imagesize 800:800 -print 1_e33_deform
Info   : ---------------------------------------------------------------
Error  : ../1_uniaxial.sim: no such file.
./postprocess.sh：行 26: 64472 已放弃               neper --rcfile none -V ../1_uniaxial.sim -simstep 4 -datanodecoo coo -dataelt1drad 0.004 -dataelt3dedgerad 0.0015 -datanodecoofact 10 -dataelt3dcol strain-el33 -dataeltscaletitle "Strain 33 (-)" -dataeltscale 0.000:0.001:0.002:0.003:0.004 -showelt1d all -cameraangle 13.5 -imagesize 800:800 -print 1_e33_deform
./postprocess.sh: 行 30: gnuplot：未找到命令

**Comment by rquey** [comment]
This is not all of the terminal output. Please provide the FEPX terminal output, as it contains helpful information (not only whether it worked or not, but also - simply - the version you used).

**Comment by fzw9381** [comment]
Thanks a lot for your reply.

My operating system is Ubuntu 20.04.
The version of FEPX is Version 1.1.1
The version of NEPER is 4.0.0

The following is FEPX terminal output:

==========================    F   E   P   X   ==========================
Info   : A finite element software package for polycrystal plasticity.
Info   : Version 1.1.1
Info   : Running on 1 cores.
Info   : <https://fepx.info>
Info   : Copyright (C) 1996-2020, DPLab, ACME Lab.
Info   : ---------------------------------------------------------------
Info   : Start time: 2021-3-19 at 16:51
Info   : Loading simulation...
Info   :   [i] Parsing file `simulation.config'...
Info   :   - Material parameters:
Info   :     > number_of_phases 1
Info   :     > phase 1 - crystal type: FCC
Info   :     > m             0.500000E-01
Info   :     > gammadot_0    0.100000E+01
Info   :     > h_0           0.200000E+03
Info   :     > g_0           0.210000E+03
Info   :     > g_s0          0.330000E+03
Info   :     > m_prime       0.500000E-02
Info   :     > gammadot_s0   0.500000E+11
Info   :     > n             0.100000E+01
Info   :     > c11           0.245000E+06
Info   :     > c12           0.155000E+06
Info   :     > c44           0.625000E+05
Info   :   [i] Parsed file `simulation.config'.
Info   :   [i] Parsing file `simulation.msh'...
Info   :   - Mesh parameters:
Info   :     > Node number: 13197
Info   :     > Elt  number: 8708
Info   :   [i] Parsed file `simulation.msh'.
Info   :   - Initializing boundary conditions...
Info   : Initializing simulation...
Info   :   - Initializing parallel gather/scatter routines...
Info   :   - Initializing fields from isotropic viscoplastic solution
Info   :     > ITMETHOD_VP: Iteration 1
Info   :       . Solving NL iteration... R = 0.6576E+00 (316 iters)
Info   :     > ITMETHOD_VP: Iteration 2
Info   :       . Solving NL iteration... R = 0.1097E+00 (336 iters)
Info   :     > Converged in 2 iterations
Info   :     > Ready for anisotropic elasto-viscoplastic simulation.
Info   : Running step 1...
Info   :   - Increment 1: t = 0.1250 secs, dt = 0.1250 secs
Info   :     > ITMETHOD_EVPS: Iteration 1
Info   :       . Solving SA iteration... R = 0.2212E+00 (446 iters)
Info   :     > ITMETHOD_EVPS: Iteration 2
Info   :       . Solving SA iteration... R = 0.1949E-03 (387 iters)
Info   :     > Converged in 2 iterations
Info   :       . Loads on control surface:  0.3763  -0.7805  205.8280  
Info   :   - Increment 2: t = 0.2500 secs, dt = 0.1250 secs
Info   :     > ITMETHOD_EVPS: Iteration 1
Info   :       . Solving SA iteration... R = 0.3570E-01 (465 iters)
Info   :     > ITMETHOD_EVPS: Iteration 2
Info   :       . Solving SA iteration... R = 0.1259E-01 (465 iters)
Info   :     > ITMETHOD_EVPS: Iteration 3
Info   :       . Solving SA iteration... R = 0.5254E-02 (467 iters)
Info   :     > ITMETHOD_EVPS: Iteration 4
Info   :       . Solving NR iteration... R = 0.4659E-02 (542 iters)
Info   :     > ITMETHOD_EVPS: Iteration 5
Info   :       . Solving NR iteration... R = 0.2407E-04 (512 iters)
Info   :     > Converged in 5 iterations
Info   :       . Loads on control surface:  0.7947  -1.6121  374.8398  
Info   :   - Increment 3: t = 0.3750 secs, dt = 0.1250 secs
Info   :     > ITMETHOD_EVPS: Iteration 1
Info   :       . Solving SA iteration... R = 0.8108E-01 (479 iters)
Info   :     > ITMETHOD_EVPS: Iteration 2
Info   :       . Solving SA iteration... R = 0.2688E-01 (490 iters)
Info   :     > ITMETHOD_EVPS: Iteration 3
Info   :       . Solving SA iteration... R = 0.1293E-01 (492 iters)
Info   :     > ITMETHOD_EVPS: Iteration 4
Info   :       . Solving SA iteration... R = 0.7285E-02 (489 iters)
Info   :     > ITMETHOD_EVPS: Iteration 5
Info   :       . Solving NR iteration... R = 0.1403E-01 (656 iters)
Info   :     > ITMETHOD_EVPS: Iteration 6
Info   :       . Solving NR iteration... R = 0.3526E-03 (643 iters)
Info   :     > Converged in 6 iterations
Info   :       . Loads on control surface:  1.2603  -2.0302  430.1652  
Info   :   - Increment 4: t = 0.5000 secs, dt = 0.1250 secs
Info   :     > ITMETHOD_EVPS: Iteration 1
Info   :       . Solving SA iteration... R = 0.2260E-01 (483 iters)
Info   :     > ITMETHOD_EVPS: Iteration 2
Info   :       . Solving SA iteration... R = 0.7576E-02 (484 iters)
Info   :     > ITMETHOD_EVPS: Iteration 3
Info   :       . Solving NR iteration... R = 0.1261E-01 (710 iters)
Info   :     > ITMETHOD_EVPS: Iteration 4
Info   :       . Solving NR iteration... R = 0.2766E-03 (681 iters)
Info   :     > Converged in 4 iterations
Info   :       . Loads on control surface:  1.3402  -2.4722  449.8639  
Info   :     > Converged on increment 4
Info   :     > Loads on X0:   -25.682071   -2.232118   -4.430158
Info   :       Loads on X1:    19.457590    1.020302   -2.106266
Info   :       Loads on Y0:     0.119616  -21.963042    1.839193
Info   :       Loads on Y1:    -0.529761   19.156686   -2.263581
Info   :       Loads on Z0:    -4.421258    4.431906 -457.816535
Info   :       Loads on Z1:     1.340205   -2.472227  449.863888
Info   : Running step 2...
Info   :   - Increment 5: t = 0.6250 secs, dt = 0.1250 secs
Info   :     > ITMETHOD_EVPS: Iteration 1
Info   :       . Solving SA iteration... R = 0.7509E-02 (478 iters)
Info   :     > ITMETHOD_EVPS: Iteration 2
Info   :       . Solving NR iteration... R = 0.8716E-02 (724 iters)
Info   :     > ITMETHOD_EVPS: Iteration 3
Info   :       . Solving NR iteration... R = 0.1422E-03 (707 iters)
Info   :     > Converged in 3 iterations
Info   :       . Loads on control surface:  1.3267  -2.9466  460.1264  
Info   :   - Increment 6: t = 0.7500 secs, dt = 0.1250 secs
Info   :     > ITMETHOD_EVPS: Iteration 1
Info   :       . Solving SA iteration... R = 0.4070E-02 (479 iters)
Info   :     > ITMETHOD_EVPS: Iteration 2
Info   :       . Solving NR iteration... R = 0.5544E-02 (692 iters)
Info   :     > ITMETHOD_EVPS: Iteration 3
Info   :       . Solving NR iteration... R = 0.8299E-04 (728 iters)
Info   :     > Converged in 3 iterations
Info   :       . Loads on control surface:  1.3016  -3.2375  466.8088  
Info   :   - Increment 7: t = 0.8750 secs, dt = 0.1250 secs
Info   :     > ITMETHOD_EVPS: Iteration 1
Info   :       . Solving SA iteration... R = 0.2567E-02 (478 iters)
Info   :     > ITMETHOD_EVPS: Iteration 2
Info   :       . Solving NR iteration... R = 0.3824E-02 (748 iters)
Info   :     > ITMETHOD_EVPS: Iteration 3
Info   :       . Solving NR iteration... R = 0.6581E-04 (745 iters)
Info   :     > Converged in 3 iterations
Info   :       . Loads on control surface:  1.2874  -3.3972  471.7321  
Info   :   - Increment 8: t = 1.0000 secs, dt = 0.1250 secs
Info   :     > ITMETHOD_EVPS: Iteration 1
Info   :       . Solving SA iteration... R = 0.1765E-02 (475 iters)
Info   :     > ITMETHOD_EVPS: Iteration 2
Info   :       . Solving NR iteration... R = 0.2817E-02 (742 iters)
Info   :     > ITMETHOD_EVPS: Iteration 3
Info   :       . Solving NR iteration... R = 0.5504E-04 (761 iters)
Info   :     > Converged in 3 iterations
Info   :       . Loads on control surface:  1.2704  -3.5326  475.6598  
Info   :     > Converged on increment 8
Info   :     > Loads on X0:   -30.736896   -2.926997   -6.358280
Info   :       Loads on X1:    22.994472    1.780360   -3.600847
Info   :       Loads on Y0:    -0.085212  -25.421533    1.534680
Info   :       Loads on Y1:     0.286413   22.633116   -3.048711
Info   :       Loads on Z0:    -5.066896    6.471126 -486.177133
Info   :       Loads on Z1:     1.270418   -3.532606  475.659797
Info   : Running step 3...
Info   :   - Increment 9: t = 1.2500 secs, dt = 0.2500 secs
Info   :     > ITMETHOD_EVPS: Iteration 1
Info   :       . Solving SA iteration... R = 0.2033E-02 (499 iters)
Info   :     > ITMETHOD_EVPS: Iteration 2
Info   :       . Solving NR iteration... R = 0.4032E-02 (920 iters)
Info   :     > ITMETHOD_EVPS: Iteration 3
Info   :       . Solving NR iteration... R = 0.1381E-03 (902 iters)
Info   :     > Converged in 3 iterations
Info   :       . Loads on control surface:  1.1741  -3.7872  481.8288  
Info   :   - Increment 10: t = 1.5000 secs, dt = 0.2500 secs
Info   :     > ITMETHOD_EVPS: Iteration 1
Info   :       . Solving SA iteration... R = 0.1639E-02 (503 iters)
Info   :     > ITMETHOD_EVPS: Iteration 2
Info   :       . Solving NR iteration... R = 0.3237E-02 (941 iters)
Info   :     > ITMETHOD_EVPS: Iteration 3
Info   :       . Solving NR iteration... R = 0.1250E-03 (942 iters)
Info   :     > Converged in 3 iterations
Info   :       . Loads on control surface:  1.1329  -3.9791  486.7055  
Info   :     > Converged on increment 10
Info   :     > Loads on X0:   -33.546477   -2.891010   -7.040467
Info   :       Loads on X1:    24.857906    2.050038   -4.420016
Info   :       Loads on Y0:    -0.397996  -28.159329    1.770103
Info   :       Loads on Y1:     0.589911   23.869681   -2.482375
Info   :       Loads on Z0:    -6.153752    6.898896 -498.310433
Info   :       Loads on Z1:     1.132921   -3.979101  486.705538
Info   : Running step 4...
Info   :   - Increment 11: t = 1.7500 secs, dt = 0.2500 secs
Info   :     > ITMETHOD_EVPS: Iteration 1
Info   :       . Solving SA iteration... R = 0.1515E-02 (497 iters)
Info   :     > ITMETHOD_EVPS: Iteration 2
Info   :       . Solving NR iteration... R = 0.2761E-02 (954 iters)
Info   :     > ITMETHOD_EVPS: Iteration 3
Info   :       . Solving NR iteration... R = 0.1131E-03 (955 iters)
Info   :     > Converged in 3 iterations
Info   :       . Loads on control surface:  1.0932  -4.1024  490.7669  
Info   :   - Increment 12: t = 2.0000 secs, dt = 0.2500 secs
Info   :     > ITMETHOD_EVPS: Iteration 1
Info   :       . Solving SA iteration... R = 0.1463E-02 (496 iters)
Info   :     > ITMETHOD_EVPS: Iteration 2
Info   :       . Solving NR iteration... R = 0.2411E-02 (969 iters)
Info   :     > ITMETHOD_EVPS: Iteration 3
Info   :       . Solving NR iteration... R = 0.9994E-04 (971 iters)
Info   :     > Converged in 3 iterations
Info   :       . Loads on control surface:  1.0146  -4.2321  494.2846  
Info   :     > Converged on increment 12
Info   :     > Loads on X0:   -35.545438   -3.342673   -7.247325
Info   :       Loads on X1:    26.509228    2.293219   -4.726407
Info   :       Loads on Y0:    -0.527069  -30.315708    1.797051
Info   :       Loads on Y1:     0.658579   24.624625   -2.065489
Info   :       Loads on Z0:    -7.333761    7.194088 -506.609272
Info   :       Loads on Z1:     1.014581   -4.232065  494.284640
Info   : Final step terminated. Simulation completed successfully.
========================================================================

**Comment by mkasemer** [comment]
So, the simulation seems to run successfully, meaning this is not an issue with FEPX. The error clearly occurs when you run a Neper (`-S`) command.

You state you are using Neper v4, but your terminal output shows:

`Info : Version 3.5.3-209-neper-fepx`

I suspect this is a version issue, and perhaps due to bad linking or pathing, if you have installed a newer version. Can you please try running using v4?

**Comment by rquey** [comment]
> `Info : Version 3.5.3-209-neper-fepx`

I think this is actually what the very first version 4 (4.0.0) was printing (the version number had not been not updated properly).

Anyway, please try again with the most recent Neper and FEPX versions.

**Comment by mkasemer** [comment]
@fzw9381 - was the resolved when you used the most up to date version of Neper?

**Comment by acmelab-ua** [comment]
I am closing this issue as it relates to post-processing rather than FEPX.
