### ISSUE TITLE
Can't run my own simulation file

### ISSUE THREAD

**Issue by RichardPA** [acmelab-ua/FEPX#7]
Hi, I am having trouble getting FEPX to run on some simple models I made through Neper. I have copied a simulation file, edited it, and then moved it into the directory with my Neper model.
I open ubuntu and made sure I was in the correct folder, then type 'fepx' in ubuntu to run the program without a job scheduler. 
I end up with an Error: 'IO Failure to open post.force.' I also notice that the Elt number is 0 when the mesh file contains 2197 elements. 
![fepx_code_no_work](https://user-images.githubusercontent.com/81585331/112881443-87978580-9080-11eb-8221-95238f0a7004.png)
It also printed blank result files for the outputs I requested.
![fepx_code_no_work2](https://user-images.githubusercontent.com/81585331/112881630-c75e6d00-9080-11eb-80ff-f52c3c6d2dd0.png)

If anyone has any suggestions, I would highly appreciate them. 

Thank you,
Richard

**Comment by rquey** [comment]
What is your Neper version / command?

**Comment by RichardPA** [comment]
My neper version is 4.1.2
![image](https://user-images.githubusercontent.com/81585331/112883171-c595a900-9082-11eb-94a1-38908997e293.png)

**Comment by mkasemer** [comment]
Hi @RichardPA 

Would you mind opening a thread under "discussions" rather than "issues"? When you do, please give a full sequence of events that you used to create the input for FEPX and run a simulation, including all explicit commands issued. That will help us pinpoint any potential issues. Thanks!

**Comment by RichardPA** [comment]
Hello @mkasemer,

Yes, that makes sense, sorry about that. Thank you!
